"""Freeze the codex_proxy import surface used by the test suite."""

from __future__ import annotations

import codex_proxy
import gateway_errors
import gateway_settings
import gateway_sse
import route_plan
import route_primitives

# One-time scan of tests/ imports, attributes, and patch targets.
# Stdlib/vendor module attributes (json, sys, urllib3, ...) are excluded.
FROZEN_CODEX_PROXY_NAMES = (
    'AttemptRequestBodyMode',
    'AuthenticationStrategy',
    'BEHAVIOR_CODEX_APP_EXTERNAL_ADAPTER',
    'BEHAVIOR_EXTERNAL_PROVIDER_GATEWAY',
    'BEHAVIOR_OFFICIAL_CODEX_APP_HTTP_PASSTHROUGH',
    'BEHAVIOR_OFFICIAL_GATEWAY_COMPAT',
    'BEHAVIOR_THIRD_PARTY_APP_TRANSPARENT_METERED',
    'CODEX_SEMANTIC_EXTERNAL_ADAPTER',
    'CODEX_SEMANTIC_NONE',
    'COLLABORATION_BOUNDARY_ERROR_CODE',
    'CallerRequestBodyMode',
    'CapabilityState',
    'CodexCompatibilityPolicy',
    'CodexProxyHandler',
    'CollaborationBackend',
    'CompactEmptyResponseError',
    'DOWNSTREAM_STREAM_COMMIT_ALLOWLIST',
    'DOWNSTREAM_STREAM_COMMIT_SEAM_METHODS',
    'DownstreamClosedDuringImageProxyError',
    'DownstreamErrorSpec',
    'ExecutionOwner',
    'GATEWAY_DIAGNOSTIC_RECORDER',
    'GATEWAY_EVENT_WRITER',
    'GATEWAY_EVENT_WRITER_SHUTDOWN_TIMEOUT_SECONDS',
    'GatewayPreResponseBudgetExhausted',
    'GatewayRequestAdmission',
    'GatewayShutdownController',
    'GatewayUserRequestedShutdown',
    'IMAGE_PROXY_CACHE_PATH',
    'IMAGE_PROXY_PROMPT',
    'ImageProxyError',
    'MULTI_AGENT_DISCOVERY_TOOLS',
    'MULTI_AGENT_TOOL_NAMES',
    'ModelIdentityResolutionError',
    'MutationPolicy',
    'OFFICIAL_CONNECT_TIMEOUT_SECONDS',
    'OFFICIAL_HTTP_POOLS',
    'OFFICIAL_POOL_MAX_CONNECTIONS',
    'OFFICIAL_POOL_MAX_IDLE_SECONDS',
    'OFFICIAL_PROXY_POOL_MAX_IDLE_SECONDS',
    'OFFICIAL_TERMINAL_DRAIN_TIMEOUT_SECONDS',
    'POLICY_PATH',
    'PROXY_EVENT_LOG_PATH',
    'PROXY_TEXT_LOG_PATH',
    'PassthroughSseSemanticStats',
    'REPAIR_CODEX_SUBAGENT',
    'REPAIR_NONE',
    'REQUEST_KIND_GATEWAY',
    'REQUEST_KIND_TRANSPARENT',
    'RETRY_CONSERVATIVE_PRE_OUTPUT',
    'RETRY_FAILURE_PERMANENT',
    'RETRY_FAILURE_PROVIDER_OVERLOADED',
    'RETRY_FAILURE_PROVIDER_THROTTLE',
    'RETRY_FAILURE_QUICK_TRANSIENT',
    'RETRY_GATEWAY_FULL',
    'RETRY_REQUEST_COMPACT',
    'RETRY_REQUEST_IMAGE_PROXY_VISION',
    'RETRY_REQUEST_MAIN_GENERATION',
    'RETRY_SAFETY_SUPPRESSED_POST_EXPOSURE',
    'RETRY_SAFETY_SUPPRESSED_POST_WRITE',
    'ROUTE_PLAN_SCHEMA_VERSION',
    'RUNTIME_CODEX_DIR',
    'RUNTIME_PROXY_DIR',
    'RelayExecutionPlan',
    'RetryPolicy',
    'RouteMutation',
    'RoutePlan',
    'RouteProtocol',
    'RouteRuntimeFacts',
    'StreamingPolicy',
    'TOOL_SEARCH_EXPLICIT_FUNCTION_TOOL',
    'TRANSIENT_HTTP_RETRY_STATUSES',
    'ThreadingHTTPServer',
    'ToolExposureMode',
    'TransportPolicy',
    'USAGE_ASYNC_TAP',
    'USAGE_SYNC_CAPTURE',
    'USER_REQUESTED_SHUTDOWN_OUTCOME',
    'UnsupportedProtocolTranslationError',
    'UpstreamProtocolTranslationError',
    'UpstreamStreamErrorEvent',
    'UpstreamStreamIncompleteError',
    'UpstreamStreamInterruptedError',
    'UsagePolicy',
    'VISION_PROXY_TRANSPARENT_OVERLAY',
    'VisionAction',
    'VisionNetworkAction',
    'WIRE_CHAT_TO_RESPONSES',
    'WIRE_RESPONSES_TO_CHAT',
    'WIRE_TRANSPARENT',
    'WORKER_BINDING_SIGNING_ROOT',
    '_GatewayDownstreamStreamCommit',
    '_OfficialHTTPSConnection',
    '_OfficialHTTPSConnectionPool',
    '_OfficialPooledResponse',
    '_TRANSPORT_PHASE_ATTRIBUTE',
    '_UpstreamSseReaderLifecycle',
    '_activate_gateway_request',
    '_active_gateway_request',
    '_adapt_apply_patch_custom_tool_history',
    '_adapt_third_party_apply_patch_response_body',
    '_adapt_third_party_apply_patch_stream_events',
    '_bounded_empty_tool_search_terminal_calls',
    '_call_vision_model_for_image_description',
    '_capacity_retry_elapsed_limit_allows',
    '_chat_completion_to_response_body',
    '_chat_completions_request_to_responses_body',
    '_chat_completions_url',
    '_chat_messages_to_responses_input',
    '_chat_stream_chunks_have_terminal',
    '_chat_stream_chunks_to_response_events',
    '_chat_tool_choice_to_responses_tool_choice',
    '_chat_tools_to_responses_tools',
    '_codexhub_error_payload',
    '_coerce_required_subagent_tool_calls',
    '_configure_official_windows_keepalive',
    '_connection_disposition',
    '_diagnostic_connection_disposition',
    '_diagnostic_error_connection_disposition',
    '_downgrade_invalid_third_party_tool_calls',
    '_downstream_json_error_payload',
    '_downstream_sse_error_payload_for_inbound_format',
    '_enqueue_gateway_event_payload',
    '_event_context_with_request_kind',
    '_events_to_responses_body',
    '_explicit_transport_phase',
    '_external_native_responses_tool_codec',
    '_external_tool_protocol',
    '_external_tool_surface_strategy',
    '_filtered_response_headers',
    '_gateway_shutdown_controller_for_handler',
    '_guard_duplicate_multi_agent_spawn_calls',
    '_image_proxy_cache_lookup',
    '_image_proxy_cache_store',
    '_image_proxy_description_for_part',
    '_image_proxy_response_body',
    '_image_proxy_vision_upstream',
    '_is_compact_summary_payload',
    '_is_raw_reasoning_stream_event',
    '_is_reasoning_summary_stream_event',
    '_is_websocket_upgrade',
    '_local_request_authorized',
    '_model_access_path_idempotency_guaranteed',
    '_multi_agent_explicit_function_tools',
    '_normalize_third_party_tool_call',
    '_normalize_transparent_tool_schema_booleans',
    '_normalize_usage_for_event',
    '_observe_gateway_diagnostic',
    '_offer_official_passthrough_usage_line',
    '_official_pool_manager',
    '_official_proxy_url',
    '_official_socket_options',
    '_official_urlopen',
    '_open_upstream_once',
    '_open_upstream_response',
    '_parse_sse_json_payload',
    '_prepare_runtime_tool_compatibility',
    '_public_event_context',
    '_published_catalog_model',
    '_reconcile_function_call_argument_events',
    '_repair_missing_required_subagent_call_events',
    '_request_kind_from_headers_and_payload',
    '_resolve_collaboration_boundary',
    '_response_body_to_chat_completion_body',
    '_response_events_to_chat_stream_chunks',
    '_responses_events_have_terminal',
    '_responses_request_to_chat_completion_body',
    '_responses_url',
    '_restore_gateway_request',
    '_retry_attempts_for_failure_class',
    '_route_plan_event_fields',
    '_route_runtime_facts',
    '_runtime_settings_value',
    '_safe_route_endpoint_url',
    '_set_official_attempt_connection_disposition',
    '_sleep_for_retry_with_gateway_cancellation',
    '_sse_payload_bytes',
    '_strip_tools_for_compact_payload',
    '_suppress_bounded_tool_search_calls',
    '_tool_search_query_digest',
    '_upstream_failure_class',
    '_upstream_retry_attempts',
    '_usage_from_response_event',
    '_validate_reasoning_effort_for_upstream',
    '_validate_worker_binding_history',
    '_value_contains_image',
    '_write_adapter_event',
    '_write_usage_observed_body_event',
    '_write_usage_observed_event',
    'apply_image_proxy_to_responses_payload',
    'behavior_profile_for_request',
    'bind_route_plan_operational_authentication',
    'catalog_with_openai_context_guard',
    'choose_upstream',
    'codex_access_token',
    'codex_account_id',
    'compatible_request_body',
    'compatible_response_body',
    'compatible_sse_line',
    'current_catalog_data',
    'decoded_request_body',
    'enforce_text_only_image_boundary',
    'existing_generated_catalog_path',
    'extract_model',
    'flush_proxy_event_writer',
    'gateway_auto_retry_enabled',
    'gateway_auto_retry_max_attempts',
    'gateway_capacity_retry_elapsed_limit_seconds',
    'gateway_client_key',
    'gateway_downstream_retry_notice_enabled',
    'gateway_image_proxy_enabled',
    'gateway_image_proxy_model',
    'gateway_official_http_passthrough_enabled',
    'gateway_retry_delay_seconds',
    'gateway_stream_retry_elapsed_limit_seconds',
    'generated_catalog_by_slug',
    'generated_catalog_slugs',
    'load_catalog_models',
    'load_policy',
    'logger',
    'materialize_operational_authentication',
    'max_request_body_bytes',
    'model_event_sse_idle_timeout_seconds',
    'model_supports_image',
    'official_base_url',
    'official_passthrough_request_body',
    'official_upstream',
    'official_upstream_open_attempts',
    'ollama_cloud_alias_upstream_model',
    'ollama_cloud_runtime_upstream',
    'provider_scoped_path',
    'provider_scoped_route_model',
    'proxy_telemetry',
    'raw_provider_probe_requested',
    'request_context_from_headers',
    'resolve_external_model_alias',
    'resolve_ollama_cloud_model',
    'route_plan_for_request',
    'run_server',
    'should_include_model',
    'transparent_request_body',
    'transport_failure_phase',
    'try_extract_model',
    'upstream_headers',
    'upstream_timeout_seconds',
    'user_requested_shutdown_payload',
    'worker_binding_signing',
    'write_proxy_event',
)

REEXPORT_IDENTITY = {
    "RouteProtocol": route_primitives.RouteProtocol,
    "SensitiveValue": route_primitives.SensitiveValue,
    "OperationalAuthentication": route_primitives.OperationalAuthentication,
    "FrozenRequestHeaders": route_primitives.FrozenRequestHeaders,
    "CapabilityState": route_primitives.CapabilityState,
    "RETRY_GATEWAY_FULL": route_primitives.RETRY_GATEWAY_FULL,
    "ImageProxyError": gateway_errors.ImageProxyError,
    "ModelIdentityResolutionError": gateway_errors.ModelIdentityResolutionError,
    "UnsupportedRouteProtocolError": gateway_errors.UnsupportedRouteProtocolError,
    "UnqualifiedRouteProtocolError": gateway_errors.UnqualifiedRouteProtocolError,
    "GatewayPreResponseBudgetExhausted": gateway_errors.GatewayPreResponseBudgetExhausted,
    "upstream_timeout_seconds": gateway_settings.upstream_timeout_seconds,
    "gateway_client_key": gateway_settings.gateway_client_key,
    "route_plan_for_request": route_plan.route_plan_for_request,
    "RoutePlan": route_plan.RoutePlan,
    "behavior_profile_for_request": route_plan.behavior_profile_for_request,
    "_sse_payload_bytes": gateway_sse._sse_payload_bytes,
    "_parse_sse_json_payload": gateway_sse._parse_sse_json_payload,
    "_identity_failure": gateway_errors._identity_failure,
}


def test_frozen_codex_proxy_names_remain_importable() -> None:
    missing = [name for name in FROZEN_CODEX_PROXY_NAMES if not hasattr(codex_proxy, name)]
    assert missing == []


def test_extracted_gateway_names_keep_object_identity() -> None:
    drifted = {
        name: getattr(codex_proxy, name)
        for name, expected in REEXPORT_IDENTITY.items()
        if getattr(codex_proxy, name) is not expected
    }
    assert drifted == {}
