// THROWAWAY: Three overview frameworks on /?prototype=overview&variant=A|B|C.
// Question: which hierarchy best supports silent operation, quota checks and usage analysis?
import { useEffect, useState } from 'react';
import { Activity, ArrowDownLeft, ArrowUpRight, BarChart3, ChevronLeft, ChevronRight, CircleHelp, Cpu, Layers, LayoutDashboard, Monitor, Moon, Plus, Radio, Settings, ShieldCheck, Sun, X, Zap } from 'lucide-react';
import './OverviewPrototype.css';
const names = ['A · 工作台', 'B · 资源看板', 'C · 运行控制台'];
const initialProviders = [
  { name: 'OpenAI', mark: '◎', type: 'Codex 订阅', value: '72', unit: '%', detail: '5 小时窗口剩余 · 2 小时 18 分后重置', percent: 72, color: '#39a68c', requests: '1,284', tokens: '8.42M' },
  { name: 'Anthropic', mark: 'A', type: 'API 余额', value: '48.60', unit: '$', detail: '账户余额 · 今日使用 $3.24', percent: 64, color: '#c18c6a', requests: '836', tokens: '5.16M' },
  { name: 'DeepSeek', mark: 'D', type: 'API 余额', value: '126.80', unit: '¥', detail: '账户余额 · 今日使用 ¥2.18', percent: 84, color: '#6a83d8', requests: '642', tokens: '4.24M' },
  { name: 'Kimi', mark: 'K', type: 'Token 配额', value: '12', unit: '%', detail: '剩余 1.2M / 10M Token · 额度偏低', percent: 12, color: '#cb9950', requests: '86', tokens: '0.62M' },
];
const models = [ ['gpt-5.4', 'OpenAI', '1,284', '8.42M', '99.8%', '820 ms'], ['claude-sonnet-4-6', 'Anthropic', '836', '5.16M', '99.6%', '640 ms'], ['deepseek-chat', 'DeepSeek', '642', '4.24M', '99.9%', '480 ms'], ['kimi-k2.5', 'Kimi', '86', '0.62M', '98.8%', '910 ms'] ];
export default function OverviewPrototype() {
  const params = new URLSearchParams(location.search);
  const [variant, setVariant] = useState(Math.max(0, ['A','B','C'].indexOf(params.get('variant') || 'A')));
  const [dark, setDark] = useState(params.get('theme') !== 'light');
  const [page, setPage] = useState('概览');
  const [period, setPeriod] = useState('今日');
  const [dimension, setDimension] = useState('模型');
  const [providers, setProviders] = useState(initialProviders);
  const [adding, setAdding] = useState(false);
  const [providerName, setProviderName] = useState('');
  const [notice, setNotice] = useState('');
  const [detail, setDetail] = useState<string | null>(null);
  useEffect(() => {
    const url = new URL(location.href); url.searchParams.set('variant', ['A','B','C'][variant]); url.searchParams.set('theme', dark ? 'dark' : 'light'); history.replaceState(null, '', url);
  }, [variant, dark]);
  useEffect(() => {
    const key = (event: KeyboardEvent) => { if ((event.target as HTMLElement).closest('input,textarea,select,[contenteditable]')) return; if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); setVariant(v => (v + (event.key === 'ArrowRight' ? 1 : 2)) % 3); } };
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, []);
  useEffect(() => { if (!notice) return; const id = setTimeout(() => setNotice(''), 3200); return () => clearTimeout(id); }, [notice]);
  const nav = [['概览', LayoutDashboard], ['使用统计', BarChart3], ['供应商', Layers], ['客户端', Monitor], ['设置', Settings]] as const;
  const navigation = <nav>{nav.map(([label, Icon]) => <button key={label} aria-label={label} title={label} className={page === label ? 'selected' : ''} onClick={() => setPage(label)}><Icon size={17}/><span>{label}</span>{label === '供应商' && <small>{providers.length}</small>}</button>)}</nav>;
  const status = <section className="p-status"><div className="p-status-icon"><Radio size={24}/></div><div><div className="p-eyebrow">LOCAL GATEWAY</div><h2>所有请求，有序流转 <span className="p-live">运行中</span></h2><p>127.0.0.1:18080 <span>·</span> 已持续运行 3 天 16 小时</p></div><div className="p-status-right"><span className="p-live-dot"/> 3 个活跃请求<button onClick={() => setDetail('Gateway 运行详情')}>运行详情 <ArrowUpRight size={14}/></button></div></section>;
  const metrics = <div className="p-metrics">{[['请求总数', period === '今日' ? '2,848' : '18,936', '+12.8%'], ['Token 用量', period === '今日' ? '18.44M' : '126.8M', '+8.2%'], ['成功率', '99.7%', '运行稳定'], ['平均首字延迟', '720', 'ms']].map(([label,value,sub]) => <div key={label}><span>{label}</span><strong>{value}<small>{sub === 'ms' ? sub : ''}</small></strong><em>{sub !== 'ms' ? sub : '较昨日 −42 ms'}</em></div>)}</div>;
  const quota = <section className="p-quota"><div className="p-section-title"><div><h2>供应商额度 <span>{providers.length.toString().padStart(2,'0')}</span></h2><p>余量先知，工作不中断</p></div><button onClick={() => setAdding(true)}><Plus size={15}/> 添加供应商</button></div><div className="p-provider-list">{providers.map(p => <button className="p-provider" key={p.name} onClick={() => setDetail(p.name)}><span className="p-provider-mark" style={{color:p.color}}>{p.mark}</span><div className="p-provider-name"><b>{p.name}</b><span>{p.type}</span></div><div className="p-quota-number"><strong>{p.unit === '$' || p.unit === '¥' ? <small>{p.unit}</small> : null}{p.value}{p.unit === '%' ? <small>%</small> : null}</strong><span>{!p.unit ? '未知余量' : p.percent < 20 ? '需要留意' : p.unit === '%' ? '剩余可用' : '可用余额'}</span></div><div className="p-provider-meter">{p.unit === '%' ? <div className="p-track"><i style={{width:p.percent+'%',background:p.color}}/></div> : <div className="p-balance-note"><ShieldCheck size={13}/> {p.unit ? '余额查询正常' : '暂不支持查询'}</div>}<span>{p.detail}</span></div><span className="p-provider-updated">刚刚更新 <ArrowUpRight size={14}/></span></button>)}</div><div className="p-footnote"><span className="p-live-dot"/> 额度数据更新于 14:32 · 各供应商按自身计量方式展示</div></section>;
  const chart = <section className="p-chart"><div className="p-section-title"><div><h2>请求趋势</h2><p>{period} · 按小时聚合</p></div><span className="p-chart-legend"><i/> 请求量</span></div><div className="p-chart-body"><div className="p-axis"><span>300</span><span>200</span><span>100</span><span>0</span></div><div className="p-bars">{[12,18,10,8,6,11,22,38,60,47,71,58,46,84,64,74,50,68,88,59,72,48,34,22].map((h,i) => <div key={i} style={{height:(period === '今日' ? h : Math.max(8,100-h))+'%'}} title={`${i}:00 · ${h*3} 次请求`}/>)}</div></div><div className="p-axis-x"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></section>;
  const activity = <section className="p-insight"><div className="p-section-title"><h2>值得关注</h2><span className="p-count">1</span></div><div className="p-alert"><span>↘</span><div><b>Kimi 额度剩余 12%</b><p>剩余 1.2M Token，可以提前补充额度。</p><button onClick={() => setDetail('Kimi')}>查看供应商 <ArrowUpRight size={13}/></button></div></div><div className="p-quiet"><ShieldCheck size={16}/><div>其他服务运行正常<p>4 个客户端已接入 · 无认证异常</p></div></div></section>;
  const table = <section className="p-table"><div className="p-section-title"><div><h2>{dimension === '模型' ? '模型' : '供应商'}使用情况</h2><p>{period}请求分布与服务表现</p></div><div className="p-segment">{['模型','供应商'].map(d => <button className={dimension === d ? 'active' : ''} key={d} onClick={() => setDimension(d)}>{d}</button>)}</div></div><table><thead><tr>{[dimension,'请求数','Token','成功率','首字延迟'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{models.map(row => <tr key={row[0]}><td><b>{dimension === '模型' ? row[0] : row[1]}</b><span>{dimension === '模型' ? row[1] : row[0]}</span></td>{row.slice(2).map((x,i)=><td key={i}>{period === '近 7 天' && i === 0 ? (Number(x.replace(',',''))*7).toLocaleString() : x}</td>)}</tr>)}</tbody></table></section>;
  return <div className={`p-root ${dark ? 'p-dark' : 'p-light'} p-variant-${variant}`}>
    <aside className="p-sidebar"><a className="p-brand" href="?prototype=overview"><span><Layers size={22}/></span>CodexHub<small>0.2</small></a><div className="p-workspace"><span className="p-live-dot"/> 本地工作空间 <small>⌘ 1</small></div>{navigation}<div className="p-sidebar-bottom"><div><span className="p-live-dot"/> 后台守护中<small>静默运行 · 随时就绪</small></div><button onClick={() => setDetail('原型说明')}><CircleHelp size={16}/> 帮助与反馈 <ArrowUpRight size={13}/></button></div></aside>
    <div className="p-main"><header className="p-topbar"><div>工作空间 <span>/</span> {page}</div><div><span className="p-demo">设计原型 · 演示数据</span><button aria-label="切换浅色或深色" onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><span className="p-avatar">N</span></div></header><main><div className="p-page-heading"><div><div className="p-eyebrow">{variant === 1 ? 'YOUR MODELS. ONE HOME.' : variant === 2 ? 'SYSTEM / OVERVIEW' : 'WORKSPACE OVERVIEW'}</div><h1>{page === '概览' ? variant === 1 ? '一切就绪，专注创造。' : variant === 2 ? '运行总览' : '概览' : page}</h1><p>{page === '概览' ? '服务状态、资源余量与使用动态，尽在此处。' : page === '使用统计' ? '了解每一次请求流向哪里，以及它的实际表现。' : '让每个连接都有清晰的归属。'}</p></div><div className="p-heading-actions"><div className="p-segment">{['今日','近 7 天'].map(t=><button key={t} className={period === t ? 'active' : ''} onClick={() => setPeriod(t)}>{t}</button>)}</div><button aria-label="刷新演示数据" onClick={() => setNotice('演示数据已刷新 · 不连接实际服务')}><Activity size={16}/></button></div></div>
    {page === '概览' && (variant === 0 ? <>{status}{metrics}{quota}<div className="p-bottom-grid">{chart}{activity}</div></> : variant === 1 ? <>{quota}<div className="p-bottom-grid p-resource-bottom"><div>{status}{metrics}</div>{activity}</div>{chart}</> : <><div className="p-console-grid"><div>{status}{metrics}{chart}{table}</div><div>{activity}{quota}</div></div></>)}
    {page === '使用统计' && <>{metrics}{chart}{table}</>}{page === '供应商' && <>{quota}{table}</>}
    {page === '客户端' && <section className="p-placeholder"><Monitor size={32}/><h2>客户端连接</h2><p>低频配置独立放置，概览保留连接摘要。</p>{['Codex','OpenCode','Pi','Zed'].map(x=><button key={x} onClick={()=>setDetail(x)}>{x}<span className="p-live">已接入</span><ArrowUpRight size={15}/></button>)}</section>}
    {page === '设置' && <section className="p-placeholder"><Settings size={32}/><h2>设置分区</h2>{['Gateway · 端口、重试、视觉代理','应用 · 自启动、静默运行、语言','外观 · 浅色、深色、跟随系统','关于 · 版本与更新'].map(x=><button key={x} onClick={()=>setDetail(x)}>{x}<ArrowUpRight size={15}/></button>)}</section>}
    <footer className="p-page-footer"><span><ShieldCheck size={12}/> 本地运行 · 数据留在设备</span><span>CodexHub / 0.2.0 Preview</span></footer></main></div>
    {import.meta.env.DEV && <div className="p-switcher"><span className="p-switcher-label">PROTOTYPE</span><button aria-label="上一方案" onClick={()=>setVariant((variant+2)%3)}><ChevronLeft size={17}/></button><b>{names[variant]}</b><button aria-label="下一方案" onClick={()=>setVariant((variant+1)%3)}><ChevronRight size={17}/></button><i/><button onClick={()=>setDark(!dark)}>{dark ? <Moon size={14}/> : <Sun size={14}/>} {dark ? '深色' : '浅色'}</button><small>{page} · {period} · {providers.length} 个供应商</small></div>}
    {notice && <div role="status" className="p-toast"><ShieldCheck size={16}/>{notice}</div>}
    {(adding || detail) && <div className="p-overlay" onClick={()=>{setAdding(false);setDetail(null);}}><section className="p-dialog" role="dialog" aria-modal="true" aria-label={adding ? '添加供应商' : detail || ''} onClick={e=>e.stopPropagation()}><button className="p-dialog-close" aria-label="关闭" onClick={()=>{setAdding(false);setDetail(null);}}><X size={18}/></button><div className="p-eyebrow">DESIGN PREVIEW</div><h2>{adding ? '添加供应商' : detail}</h2>{adding ? <form onSubmit={e=>{e.preventDefault();if(!providerName.trim())return;setProviders([...providers,{name:providerName.trim(),mark:providerName[0].toUpperCase(),type:'自定义供应商',value:'—',unit:'',detail:'暂不支持查询 · 演示添加',percent:0,color:'#7c8aaf',requests:'0',tokens:'0'}]);setAdding(false);setProviderName('');setNotice('已添加到原型 · 未写入实际配置');}}><p>预览添加流程；不需要真实凭据。</p><label>供应商名称<input autoFocus required value={providerName} onChange={e=>setProviderName(e.target.value)} placeholder="例如：我的模型服务"/></label><label>连接地址<input placeholder="https://api.example.com/v1"/></label><div className="p-demo-callout"><Zap size={15}/> 此处模拟连接验证与模型发现，不发送网络请求。</div><button className="p-primary" type="submit">模拟验证并添加 <ArrowUpRight size={16}/></button></form> : <><p>此面板用于预览详情入口与信息层级。</p><div className="p-detail-row"><span>当前状态</span><b>{detail === 'Kimi' ? '额度偏低 · 剩余 12%' : '正常 · 演示数据'}</b></div><div className="p-detail-row"><span>数据更新时间</span><b>14:32</b></div><div className="p-demo-callout"><Cpu size={16}/> 所有数据和操作均为原型演示。当前没有连接实际 Gateway。</div><button className="p-primary" onClick={()=>{setDetail(null);setPage('使用统计');}}>查看使用统计 <ArrowDownLeft size={15}/></button></>}</section></div>}
  </div>;
}
