// THROWAWAY: test controls live here, outside the product's normal pages.
import { createContext, useContext, useState, type ReactNode } from 'react';
import { FlaskConical, RotateCcw } from 'lucide-react';
import { pt } from './PrototypeLocale';
import { clientFixtures } from './PrototypeData';
import type { PrototypeClientCondition } from './ClientDetailPrototype';
const defaults:Record<string,string>={action:'normal',codex:'normal',model:'success',usage:'normal',officialAuth:'authorized',subscription:'success',history:'normal',diagnostics:'normal',update:'available',contextGuard:'normal'};
const ScenarioContext=createContext<{values:Record<string,string>;set:(key:string,value:string)=>void;reset:()=>void}>({values:defaults,set:()=>{},reset:()=>{}});
export function PrototypeScenarioProvider({children}:{children:ReactNode}){
  const [values,setValues]=useState(defaults);
  return <ScenarioContext.Provider value={{values,set:(key,value)=>setValues(s=>({...s,[key]:value})),reset:()=>setValues(defaults)}}>{children}</ScenarioContext.Provider>;
}
export function usePrototypeScenario(key:string):[string,(value:string)=>void]{const context=useContext(ScenarioContext);return [context.values[key],value=>context.set(key,value)];}
function ScenarioField({name,label,options}:{name:string;label:string;options:Array<[string,string]>}){const [value,set]=usePrototypeScenario(name);return <label className="v-tool-field"><span>{pt(label)}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{pt(l)}</option>)}</select></label>;}
export function PrototypeTools({conditions,onCondition,onClose}:{conditions:Record<string,PrototypeClientCondition>;onCondition:(id:string,value:PrototypeClientCondition)=>void;onClose:()=>void}){
  const [tab,setTab]=useState('服务与连接');const {reset}=useContext(ScenarioContext);
  return <div className="v-tools"><div className="v-tools-intro"><FlaskConical size={18}/><div><b>{pt('仅用于原型验收')}</b><p>{pt('在这里选择演示状态，然后返回对应页面查看。不会修改真实配置。')}</p></div></div><div className="v-editor-tabs">{['服务与连接','账户与模型','设置与维护'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{pt(t)}</button>)}</div><div className="v-tools-fields">{tab==='服务与连接'&&<><ScenarioField name="action" label="下一次保存或连接操作" options={ [['normal','成功'],['failure','写入失败 · 保留原配置'],['partial','保存成功 · 部分客户端同步失败'],['restart','保存成功 · Codex 重启失败']] }/><ScenarioField name="codex" label="Codex 连接前置状态" options={ [['normal','正常'],['running','Codex 正在运行 · 重启确认'],['foreign','其他通道占用 · 接管确认'],['unsupported','当前平台不支持自动重启']] }/>{clientFixtures.map(c=><label className="v-tool-field" key={c.id}><span>{c.name}</span><select value={conditions[c.id]||'normal'} onChange={e=>onCondition(c.id,e.target.value as PrototypeClientCondition)}><option value="normal">{pt('正常')}</option><option value="drift">{pt('配置偏离')}</option><option value="unavailable">{pt('未安装 / 不可用')}</option><option value="foreign">{pt('其他通道管理')}</option></select></label>)}</>}{tab==='账户与模型'&&<><ScenarioField name="model" label="模型与端点测试" options={ [['success','成功'],['failure','认证失败']] }/><ScenarioField name="officialAuth" label="Codex 官方账户" options={ [['authorized','已授权'],['signedout','需要登录']] }/><ScenarioField name="usage" label="官方用量" options={ [['normal','正常'],['loading','正在加载'],['empty','暂无用量'],['error','查询失败']] }/><ScenarioField name="subscription" label="xAI 授权结果" options={ [['success','授权成功'],['expired','授权码过期'],['denied','无订阅资格（403）'],['error','授权服务失败']] }/></>}{tab==='设置与维护'&&<><ScenarioField name="history" label="历史同步场景" options={ [['normal','正常同步'],['locked','文件被占用'],['conflict','归属冲突'],['failure','写入失败']] }/><ScenarioField name="diagnostics" label="诊断场景" options={ [['normal','调试构建 · 正常'],['release','正式构建 · 隐藏入口'],['offline','Gateway 离线'],['loading','正在加载'],['lag','状态延迟'],['failure','操作失败']] }/><ScenarioField name="contextGuard" label="上下文保护状态" options={ [['normal','正常'],['conflict','全局覆盖冲突'],['unknown','状态未知']] }/><ScenarioField name="update" label="更新场景" options={ [['available','有可用更新'],['latest','已是最新版本'],['check-failure','检查失败'],['install-failure','安装失败']] }/></>}</div><div className="v-tools-footer"><button className="v-small-button" onClick={()=>{reset();clientFixtures.forEach(c=>onCondition(c.id,'normal'));}}><RotateCcw size={13}/>{pt('恢复默认场景')}</button><button className="v-primary small" onClick={onClose}>{pt('返回工作空间')}</button></div></div>;
}
