#!/bin/sh
# Archive desktop entries generated by older CodexHub releases.
# The package-owned /usr/share/applications entry is the sole launcher after
# migration. Backups deliberately do not end in .desktop, so menus ignore them.
set -eu

is_codexhub_generated_launcher() {
  awk '
    {
      sub(/\r$/, "")
      if ($0 == "[Desktop Entry]") { desktop = 1; next }
      if ($0 == "Type=Application") { type = 1; next }
      if ($0 == "Name=CodexHub") { name = 1; next }
      if ($0 == "Comment=CodexHub desktop backend and CLI") { comment = 1; next }
      if ($0 ~ /^Exec=.+$/) { exec += 1; exec_line = $0; next }
      if ($0 == "Icon=codexhub") { icon = 1; next }
      if ($0 == "Terminal=false") { terminal = 1; next }
      if ($0 == "Categories=Development;") { categories = 1; next }
      if ($0 == "StartupNotify=true") { startup = 1; next }
      if ($0 == "StartupWMClass=com.codexhub.app") { wmclass = 1; next }
      if ($0 == "X-GNOME-UsesNotifications=true") { notifications = 1; next }
      if ($0 == "X-CodexHub-Managed=true") { managed = 1; next }
      unknown = 1
    }
    END {
      valid_count = (NR == 11 || NR == 12)
      required = desktop && type && name && comment && exec == 1 && icon && terminal && categories && startup && wmclass && notifications
      command = substr(exec_line, 6)
      if (command ~ /^".*"$/) {
        command = substr(command, 2, length(command) - 2)
      }
      lower = tolower(command)
      count = split(lower, parts, "/")
      basename = parts[count]
      legacy_exec = lower == "/usr/bin/codexhub" \
        || (index(lower, "/src-tauri/target/") && lower ~ /\/codexhub$/) \
        || basename ~ /^codexhub.*\.appimage$/
      exit !(valid_count && required && !unknown && (managed || (NR == 11 && legacy_exec)))
    }
  ' "$1"
}

archive_launcher() {
  path=$1
  [ -f "$path" ] || return 0
  [ ! -L "$path" ] || return 0
  is_codexhub_generated_launcher "$path" || return 0

  index=0
  while [ "$index" -lt 100 ]; do
    suffix=""
    [ "$index" -eq 0 ] || suffix=".$index"
    backup="$path.codexhub-legacy-backup$suffix"
    if ln "$path" "$backup" 2>/dev/null; then
      rm -- "$path"
      return 0
    fi
    [ -e "$backup" ] || return 1
    index=$((index + 1))
  done
  return 1
}

cleanup_home() {
  home=$1
  expected_uid=$2
  apps="$home/.local/share/applications"
  for directory in "$home" "$home/.local" "$home/.local/share" "$apps"; do
    [ -d "$directory" ] || return 0
    [ ! -L "$directory" ] || return 0
    [ "$(stat -c %u "$directory")" = "$expected_uid" ] || return 0
  done
  archive_launcher "$apps/codexhub.desktop"
  archive_launcher "$apps/com.codexhub.app.desktop"
}

dispatch_cleanup() {
  uid=$1
  gid=$2
  home=$3
  if [ "$(id -u)" = "$uid" ]; then
    cleanup_home "$home" "$uid"
    return
  fi
  command -v setpriv >/dev/null 2>&1 || return 1
  setpriv \
    --reuid "$uid" \
    --regid "$gid" \
    --clear-groups \
    --bounding-set=-all \
    --inh-caps=-all \
    --ambient-caps=-all \
    --no-new-privs \
    --reset-env \
    -- "$0" --cleanup-home "$home"
}

cleanup_passwd_users() {
  allowed_prefix=$1
  minimum_uid=$2
  while IFS=: read -r _ _ uid gid _ home _; do
    case "$uid" in
      ""|*[!0-9]*) continue ;;
    esac
    case "$gid" in
      ""|*[!0-9]*) continue ;;
    esac
    [ "$uid" -ge "$minimum_uid" ] || continue
    [ "$uid" -lt 65534 ] || continue
    case "$home" in
      "$allowed_prefix"/*) ;;
      *) continue ;;
    esac
    resolved_home=$(readlink -f -- "$home" 2>/dev/null || true)
    [ "$resolved_home" = "$home" ] || continue
    dispatch_cleanup "$uid" "$gid" "$home"
  done
}

if [ "${1-}" = "--cleanup-home" ]; then
  [ "$#" -eq 2 ] || exit 2
  current_uid=$(id -u)
  [ "$current_uid" -ne 0 ] || exit 1
  cleanup_home "$2" "$current_uid"
  exit 0
fi

if [ "${1-}" = "--test-home" ]; then
  [ "$#" -eq 2 ] || exit 2
  test_uid=$(stat -c %u "$2")
  cleanup_home "$2" "$test_uid"
  exit 0
fi

if [ "${1-}" = "--test-passwd" ]; then
  [ "$#" -eq 3 ] || exit 2
  cleanup_passwd_users "$3" 0 < "$2"
  exit 0
fi

invoking_uid=${PKEXEC_UID:-${SUDO_UID:-}}
case "$invoking_uid" in
  ""|*[!0-9]*|0) invoking_uid="" ;;
esac
if [ -n "$invoking_uid" ] && { [ "$invoking_uid" -lt 1000 ] || [ "$invoking_uid" -ge 65534 ]; }; then
  invoking_uid=""
fi

if [ -n "$invoking_uid" ]; then
  passwd_entry=$(getent passwd "$invoking_uid" || true)
  [ -n "$passwd_entry" ] || exit 0
  printf '%s\n' "$passwd_entry" | cleanup_passwd_users /home 1000
  exit 0
fi

# Package managers and unattended updaters do not always preserve the caller
# UID. In that case inspect only canonical, non-system /home accounts; every
# path component is still revalidated for ownership and symlinks above.
getent passwd | cleanup_passwd_users /home 1000
