/** Canonical IPC command names. Keep in sync with generate_handler! and web_bridge.
 *  Frontend invoke goes through these constants, not raw strings.
 */
export const COMMANDS = {
  getAppFlavor: "get_app_flavor",
  getAppVersion: "get_app_version",
  checkAppUpdate: "check_app_update",
  startAppUpdateInstall: "start_app_update_install",
  getAppUpdateInstallStatus: "get_app_update_install_status",
  consumeAppUpdateCompletion: "consume_app_update_completion",
  installAppUpdate: "install_app_update",
  getStatus: "get_status",
  switchMode: "switch_mode",
  startProxy: "start_proxy",
  stopProxy: "stop_proxy",
  restartProxy: "restart_proxy",
  getProviders: "get_providers",
  saveProviders: "save_providers",
  getSettings: "get_settings",
  saveSettings: "save_settings",
  getCodexContextGuardStatus: "get_codex_context_guard_status",
  setCodexContextGuard: "set_codex_context_guard",
  refreshOfficialModels: "refresh_official_models",
  openaiUsageCompletions: "openai_usage_completions",
  discoverProviderModels: "discover_provider_models",
  probeUpstreamFormat: "probe_upstream_format",
  providerProbeUpstreamFormat: "provider_probe_upstream_format",
  testModelEndpoint: "test_model_endpoint",
  gatewayStatus: "gateway_status",
  diagnosticsStatus: "diagnostics_status",
  diagnosticsManualMark: "diagnostics_manual_mark",
  diagnosticsPause: "diagnostics_pause",
  diagnosticsResume: "diagnostics_resume",
  diagnosticsDeleteIncident: "diagnostics_delete_incident",
  gatewayTestRequest: "gateway_test_request",
  gatewayRecentEvents: "gateway_recent_events",
  gatewayUsageSnapshot: "gateway_usage_snapshot",
  gatewayUsageSummary: "gateway_usage_summary",
  gatewayUsageEvents: "gateway_usage_events",
  gatewayCopyClientConfig: "gateway_copy_client_config",
  listGatewayClients: "list_gateway_clients",
  dshClientConnect: "dsh_client_connect",
  dshClientDisconnect: "dsh_client_disconnect",
  dshClientReadback: "dsh_client_readback",
  previewGatewayClientConfig: "preview_gateway_client_config",
  applyGatewayClientConfig: "apply_gateway_client_config",
  restoreGatewayClientConfig: "restore_gateway_client_config",
  switchGatewayClientRoute: "switch_gateway_client_route",
  syncGatewayClients: "sync_gateway_clients",
  subagentMatrixStatus: "subagent_matrix_status",
  generateCatalog: "generate_catalog",
  getCatalogOverrideDiagnostics: "get_catalog_override_diagnostics",
  listModels: "list_models",
  refreshModelMetadata: "refresh_model_metadata",
  listModelMetadata: "list_model_metadata",
  saveModelMetadataOverride: "save_model_metadata_override",
  saveOfficialMultiAgentVersion: "save_official_multi_agent_version",
  listOfficialMultiAgentOverrides: "list_official_multi_agent_overrides",
  listOfficialMultiAgentBaselines: "list_official_multi_agent_baselines",
  syncHistory: "sync_history",
  reconcileAfterRouteSwitch: "reconcile_after_route_switch",
  migrateOfficialHistoryToUnified: "migrate_official_history_to_unified",
  restoreOfficialHistoryFromUnified: "restore_official_history_from_unified",
  preflightUnifiedHistory: "preflight_unified_history",
  getConversationSyncStatus: "get_conversation_sync_status",
  syncConversationHistory: "sync_conversation_history",
  diagnoseConversationHistory: "diagnose_conversation_history",
  syncCatalog: "sync_catalog",
  setAutostart: "set_autostart",
  removeAutostart: "remove_autostart",
  getAutostartStatus: "get_autostart_status",
  openCodexApp: "open_codex_app",
  windowMinimize: "window_minimize",
  windowToggleMaximize: "window_toggle_maximize",
  windowCloseToTray: "window_close_to_tray",
} as const;

export type CommandName = (typeof COMMANDS)[keyof typeof COMMANDS];

